language: php

sudo: false

php:
  - 7.1
  - 7.2
  - master

before_install:
  - composer self-update
  - composer clear-cache
  - wget -O phpunit.phar https://phar.phpunit.de/phpunit-6.4.phar

install:
  - travis_retry composer update --no-interaction --no-ansi --no-progress --no-suggest

script:
  - php phpunit.phar

notifications:
  email: false

